### ISSUE TITLE
!todo gyronny not centred on mullet

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#211]
!todo gyronny not centred on mullet
!draw argent, a mullet of 6 gyronny of 12 gules and sable

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/126802180-913c9256-5da9-4b22-aa1b-4fb8b31b049a.png)

**Comment by karlwilcox** [comment]
Fixed, sort of. If you colour a charge with a division, that division is now created in a square shape and it is scaled to fit the **Bounding Box** of the charge (the bounding box is the smallest box that will enclose the whole charge). Hence, if the centre of that bounding box lines up with the centre of the charge then everything works fine (try it in a roundel for example). The problem with mullets is that their bounding boxes are NOT square so the division will not line up neatly, although it is much better than it was.

The longer term fix is probably to add a "center point" meta-data attribute to charges so that they can define their own center points around which divisions should be scaled, but to be honest there are probably more widely applicable things to be getting on with!

**Comment by karlwilcox** [comment]
Now on live server

**Comment by ericscheid** [comment]
Currently not fixed.

`!draw murrey a mullet gyronny sa and or`

![image](https://user-images.githubusercontent.com/2605467/163291539-03e5b6fc-dea1-482a-bb21-0226ef862560.png)
